import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LayoutInstructor } from "@/components/layouts/layout-bar.comp";
import { BookOpenIcon, ChatBubbleLeftIcon, UserGroupIcon } from "@heroicons/react/16/solid";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const menu = [{
  text: 'Manage Student',
  href: '/instructor/students',
  icon: <UserGroupIcon width={20} height={20} />,
},
{
  text: 'Manage Lesson',
  href: '/instructor/lessons',
  icon: <BookOpenIcon width={20} height={20} />,
},
{
  text: 'Chating',
  href: '/instructor/chat',
  icon: <ChatBubbleLeftIcon width={20} height={20} />,
},
]
export default function InstructorRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutInstructor menu={menu}>
      {children}
    </LayoutInstructor>
  );
}
