import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../globals.css'
import StyleRoot from "@/base/ui/style-root";
import ReactQueryProvider from "@/base/react-query/provider";
import { LayoutInstructor } from "@/components/layouts/layout-bar.comp";
import { BookOpenIcon, ChatBubbleLeftIcon } from "@heroicons/react/16/solid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const menu = [{
        text: 'My Lessons',
        href: '/student/lessons',
        icon: <BookOpenIcon width={20} height={20} />,
    },
    {
        text: 'Massage',
        href: '/chat',
        icon: <ChatBubbleLeftIcon width={20} height={20} />,
    },
    ]
export default function StudentRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
                <StyleRoot>
                  <LayoutInstructor menu={menu}>
                    {children}
                  </LayoutInstructor>
                </StyleRoot>
              </ReactQueryProvider>
      </body>
    </html>
  );
}
